version: "3.8"
services:
  react:
    build:
      context: .
      dockerfile: react.Dockerfile
      args:
        #Passing .env variable to Dockerfile ARG
        - ROOT_URL=${REACT_APP_ROOT_URL}
    container_name: react
    ports:
      - 80:80
